apiVersion: v1
kind: Namespace
metadata:
  name: <replace> ##Replace this with the name of you namespace.
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-example
  namespace: <replace> ##Replace this with the name of you namespace.
  labels:
    app: nginx-example
spec:
  containers:
    - name: nginx-example
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-example-service
  namespace: <replace> ##Replace this with the name of you namespace.
spec:
  type: NodePort
  selector:
    app: nginx-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
